### ISSUE TITLE
Error download youtube-dl.exe

### ISSUE THREAD

**Issue by Tox86** [obscurename/youtube-dl-gui#1]
Hi this is a bug:

[error.txt](https://github.com/obscurename/youtube-dl-gui/files/1016616/error.txt)

Greetings.

**Comment by obscurename** [comment]
I can't seem to reproduce it.

Technical, the way it gathers the version to download is through HTML "parsing", [see this line in the master](https://github.com/obscurename/youtube-dl-gui/blob/master/Classes/GlobalFunctions.cs#L20), and it still returns a correct release date. You may not have access to the [site it parses from](https://rg3.github.io/youtube-dl/download.html)

[Try to download it manually from here](https://github.com/rg3/youtube-dl/releases/latest)

Sorry for being late.

**Comment by Tox86** [comment]
![bug](https://user-images.githubusercontent.com/7013508/27367692-92c5ff88-561c-11e7-97fa-42d317536c58.PNG)

**Comment by obscurename** [comment]
Do you use a real time virus scanner? It might be scanning that file. The only program that should be using that file should be my program, but it's being used elsewhere. You can manually rename it to "youtube-dl.exe" and try again.

**Comment by Tox86** [comment]
Defender.

**Comment by obscurename** [comment]
Have you tried renaming it, etc?
