### ISSUE TITLE
Downloading videos with a custom format does not work

### ISSUE THREAD

**Issue by obscurename** [obscurename/youtube-dl-gui#13]
TBD

Using "best" still works, stick with that.

**Comment by XanGregor** [comment]
This is the best downloader that I've tried so far, and I've tried tons of them. Simple and straight to the point.
Keep up the good work!

**Comment by obscurename** [comment]
[fixed in v1.61](https://github.com/murrty/youtube-dl-gui/commit/07788f3ae4f1cd7b5e927ee5d44ed62d01000037#diff-c35fbb5c8fc722c9fec8dbbd5b1e00fdR113)
