### ISSUE TITLE
error when opening

### ISSUE THREAD

**Issue by nomplik** [obscurename/youtube-dl-gui#2]
using XP,SP2
have tested command prompt version youtube-dl.exe and working

downloaded/saved ver. 1.1.2.0 - youtube-dl-gui.exe to folder C:\XYZ (folder contains ffmpeg.exe)
attempting to open/run generates a "not a valid win32 application"

Maybe App not supported by XP,SP2 ?

Thank you

**Comment by ewwink** [comment]
it use .net framework 4.5 that not available in XP, you need to compile in .net 4.0
