### ISSUE TITLE
if u choose download as audio & choose aac/m4a format, download/convert will always fail if bestaudio is webm instead of m4a (for some youtube video)...

### ISSUE THREAD

**Issue by demonluo** [obscurename/youtube-dl-gui#8]
if u choose download as audio & choose aac/m4a format, download/convert will always fail if bestaudio is webm instead of m4a (for some youtube video)...

eg, http://www.youtube.com/watch?v=L8eRzOYhLuw

**Comment by obscurename** [comment]
Any non-default audio formats will require FFmpeg. It's a limitation of youtube-dl and not my program, sorry. I have downloaded (successfully) your example in .aac, and .m4a, results were FFmpeg was used. I recommend downloading FFmpeg.
